### PR TITLE
Add a "hidden" option to thaumcraft research

### PR DESCRIPTION
**Pull request by xchgeax**
"MC1.7.10 end of life." 
Remember that? jaredlll08/ModTweaker#212

MC1.7.10 is a life.

### CODE REVIEW

**Comment by vlaetansky** [comment]
WIP

**Comment by Dream-Master** [comment]
Hehe finally

**Review by boubou19 — APPROVED** [review]

**Comment by AnrDaemon** [comment]
Hidden is nice, thank you. What about "Lost" research?

**Comment by Dream-Master** [comment]
Haha old conversation 😎

**Comment by Dream-Master** [comment]
If I want something for gtnh I get it even 7 years later 😎

**Comment by AnrDaemon** [comment]
Benefits of the OSS.

**Pull request merged**
